version: "3.9"
services:
  php:
    build:
      context: _docker/php/dev
    env_file:
      - _env/php.env
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./_docker/php/dev/base.ini:/usr/local/etc/php/conf.d/base.ini
      - ./:/app
    ports:
      - "8888:8888"
    command: php -S 0.0.0.0:8888 -t /app/public/
  postgres:
    image: postgres:15-alpine
    env_file:
      - _env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
volumes:
  postgres_data:
